[package]
name = "reflist"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Joan Marcè i Igual <@jmigual>"]
license = "MIT"
repository = "https://github.com/jmigual/typst-reflist"
keywords = ["typst", "list", "referenceable"]
compiler = "0.11.0"
description = "A simple referenceable list library for typst."
exclude = ["examples/*", "img/*"]
